"""create field updated_at in Debt model

Revision ID: e6fa39de6d68
Revises: 424ddbd8306c
Create Date: 2026-05-03 22:23:38.997433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fa39de6d68'
down_revision: Union[str, None] = '424ddbd8306c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'updated_at')
    # ### end Alembic commands ###
